example1 = {
    "trace": [
        {
            "module_output": {
                "id": 31,
                "prediction": 0,
                "statement": "Vice President Kamala Harris’ mother “worked the MK Ultra program” and was “involved in secret mind-control experiments.”",
                "values": {
                    "us_vs_them_lang": {"shap_value": 0.043, "feature_value": 2},
                    "exaggerated_uncertainty": {
                        "shap_value": 0.0021,
                        "feature_value": 0.8,
                    },
                    "source_quality": {"shap_value": 0.3172, "feature_value": 2},
                    "victim_villain_language": {
                        "shap_value": 0.0241,
                        "feature_value": 0,
                    },
                    "black_and_white_language": {
                        "shap_value": 0.0127,
                        "feature_value": 1,
                    },
                    "dehumanization": {"shap_value": 0.1046, "feature_value": 1},
                    "emotionality": {"shap_value": 0.0292, "feature_value": -0.5},
                    "reading_difficulty": {"shap_value": 0.0081, "feature_value": 0.4},
                    "sentiment": {"shap_value": -0.0052, "feature_value": -1},
                    "polarization": {"shap_value": 0.1301, "feature_value": 1},
                },
                "top_features": [
                    "source_quality",
                    "polarization",
                    "dehumanization",
                    "us_vs_them_lang",
                    "emotionality",
                    "victim_villain_language",
                    "black_and_white_language",
                    "reading_difficulty",
                    "sentiment",
                    "exaggerated_uncertainty",
                ],
            },
            "action": "individual feature importance",
            "summary": "Top feature contributions: source_quality (0.32, value=2.0), polarization (0.13, value=1.0), dehumanization (0.10, value=1.0), us_vs_them_lang (0.04, value=2.0). High values in source_quality (no evidence), polarized language, and dehumanization indicate concerning content patterns despite the model's False prediction.",
            "laymans_summary": "The post says harmful things without proof (source quality at 2.0), uses disrespectful language to call opponents 'bad' (dehumanization at 1.0), and says everything is 'black and white' (polarization at 1.0), making it risky even though the model didn't flag it as dangerous.",
            "module_name": "individual feature importance",
            "module_params": {},
        },
        {
            "module_output": {
                "counts": [22, 85, 77],
                "edges": [0, 0.6666666666666666, 1.3333333333333333, 2],
            },
            "action": "feature distribution for source_quality (label: False)",
            "summary": "Feature distribution counts [22, 85, 77] across bins defined by edges [0.0, 0.67, 1.33, 2.0].",
            "laymans_summary": "The data is split into three groups: 22 posts have low scores, 85 have medium scores, and 77 have high scores.",
            "module_name": "feature distribution",
            "module_params": {"feature_name": "source_quality", "label": "False"},
        },
        {
            "module_output": "| source_quality ↓ \\ polarization → | 0.00–0.20 | 0.20–0.40 | 0.40–0.60 | 0.60–0.80 | 0.80–1.00 |\n| --- | --- | --- | --- | --- | --- |\n| 0.00–0.67 | 19 | 0 | 0 | 0 | 3 |\n| 0.67–1.33 | 18 | 18 | 10 | 6 | 33 |\n| 1.33–2.00 | 16 | 6 | 5 | 3 | 47 |",
            "action": "feature distribution 2D for source_quality, polarization (label: False)",
            "summary": "The datapoint (source_quality=2.0, polarization=1.0) falls into the feature distribution cell [source_quality 1.33–2.00, polarization 0.80–1.00] with 47 instances, indicating high polarization paired with no verifiable evidence.",
            "laymans_summary": "This post has no evidence (source quality 2.0) and is extremely divisive (polarization 1.0), matching 47 other posts in the same highly polarizing category.",
            "module_name": "feature distribution 2D",
            "module_params": {
                "feature_name_1": "source_quality",
                "feature_name_2": "polarization",
                "label": "False",
            },
        },
        {
            "module_output": {
                "accuracy": 0.65,
                "f1_score": 0.6482,
                "precision": 0.6531,
                "recall": 0.65,
            },
            "action": "performance metrics",
            "summary": "Accuracy: 0.65, F1 Score: 0.6482, Precision: 0.6531, Recall: 0.65",
            "laymans_summary": "The model gets about 65% of its answers right overall, correctly identifying most cases without too many mistakes, like getting 65 out of 100 questions correct on a quiz.",
            "module_name": "performance metrics",
            "module_params": {},
        },
        {
            "module_output": {
                "confusion": [
                    [0.64, 0.21, 0.15],
                    [0.18, 0.66, 0.16],
                    [0.23, 0.12, 0.65],
                ],
                "note": "First column/row is the False label, second column/row is the Neither label and third column/row is the True label.",
            },
            "action": "confusion matrix",
            "summary": "Confusion matrix accuracy: False (64%), Neither (66%), True (65%). Highest accuracy on Neither posts (66%), followed by True (65%) and False (64%).",
            "laymans_summary": "The model correctly identified False posts 64% of the time, Neither posts 66% of the time, and True posts 65% of the time.",
            "module_name": "confusion matrix",
            "module_params": {},
        },
        {
            "module_output": {
                "label": 0,
                "values": {
                    "us_vs_them_lang": 0.04,
                    "exaggerated_uncertainty": 0.1,
                    "source_quality": 0.38,
                    "victim_villain_language": 0.06,
                    "black_and_white_language": 0.02,
                    "dehumanization": 0.07,
                    "emotionality": 0.07,
                    "reading_difficulty": 0.08,
                    "sentiment": 0.05,
                    "polarization": 0.13,
                },
                "top_features": [
                    "source_quality",
                    "polarization",
                    "exaggerated_uncertainty",
                ],
            },
            "action": "global feature importance (label: False)",
            "summary": "Top global feature importances: source_quality (0.38), polarization (0.13), exaggerated_uncertainty (0.10).",
            "laymans_summary": "The main reasons the model made its decision were how reliable the sources were (source quality, 0.38), how divided the language was (polarization, 0.13), and how certain the claims seemed (exaggerated uncertainty, 0.10).",
            "module_name": "global feature importance",
            "module_params": {"label": "False"},
        },
        {
            "module_output": {
                "feature": "source_quality",
                "class": "False",
                "grid_values": [0, 1, 2],
                "average": [0.2631289430345656, 0.2798342646031376, 0.7477111303375537],
            },
            "action": "partial dependence plot for source_quality (label: False)",
            "summary": "source_quality grid_values [0, 1, 2] correlate with average predicted probability for class 'False' as [0.263, 0.280, 0.748]. The data point's source_quality=2.0 aligns with the highest probability (0.748) for prediction 'False'.",
            "laymans_summary": "When a post has no evidence to back up its claims (source_quality=2), the model is most likely to predict it's False (about 75% chance), compared to posts with specific evidence (source_quality=0) which have only a 26% chance of being False.",
            "module_name": "partial dependence plot",
            "module_params": {"feature_name": "source_quality", "label": "False"},
        },
    ],
    "conclusion": {
        "judgement_rating": 0,
        "judgement_reason": "The model predicted the statement as False (label 0), but multiple local explanation modules strongly indicate that the statement exhibits high-risk content patterns. Key features like source_quality (value=2.0, indicating no verifiable evidence), polarization (value=1.0), and dehumanization (value=1.0) are among the top contributors to the prediction, yet they were not sufficient to override the model's False label despite being highly concerning. The partial dependence plot confirms that a source_quality of 2.0 corresponds to a high predicted probability (74.8%) of being False, which should have triggered a stronger caution. However, the model failed to recognize the danger in the statement, showing a critical trustworthiness failure in the face of clear indicators of harmful content. Additionally, the model's overall accuracy (65%) is only moderate, further reducing confidence. Thus, the prediction is untrustworthy despite the local explanations pointing to high risk.",
        "judgement_reason_short": "The model ignored strong warning signs like no evidence and extreme polarization, despite the explanations showing it should have flagged the statement as dangerous.",
        "most_relevant_modules": ["partial dependence plot", "feature distribution 2D"],
    },
}
